FROM python:3.12-slim

RUN apt-get update && apt-get install -y docker.io && apt-get clean

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .
COPY linux_simulation.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]